language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev

matrix:
  include:
    - php: 7.2
      env: DB=PGSQL
    - php: 7.3
      env: DB=MYSQL
    - php: 7.4
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update silverstripe/recipe-cms:^4
  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.x-dev --no-update; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile


script:
  - vendor/bin/phpunit --testsuite recipe-elemental-bootstrap
